export const SET_USER_DATA = "USERS/SET_USER_DATA";
export const SET_CHOOSED_USER = "USER/SET_CHOOSED_USER";
export const SET_SEARCH_LINE = "USER/SET_SEARCH_LINE";
export const SET_USERS_SEARCH = "USER/SET_USERS_SEARCH";